root = "."  
tmp_dir = "tmp"  

[build]
  cmd = "go build -o tmp/main.exe cmd/main.go"  
  bin = "tmp/main"  
  full_bin = "tmp/main"  
  delay = 1000  # Delay 1 sec
  exclude_dir = ["vendor", "tmp"]
  include_ext = ["go", "tpl", "tmpl", "html"]

[log]
  level = "debug"
